blank_issues_enabled: false
contact_links:
  - name: Question or Problem
    about: Ask a question or ask about a problem in GitHub Discussions.
    url: https://github.com/ajutamangdev/pysecfw/discussions/categories/q-a
  - name: Feature Request
    about: To suggest an idea or ask about a feature, please start with a question saying what you would like to achieve. There might be a way to do it already.
    url: https://github.com/ajutamangdev/pysecfw/discussions/categories/ideas
